config/routes.rb
Analysistool::Application.routes.draw do

  resources :gpsejemplos do
    collection do
      get :rutas
    end
  end

  resources :locations do
    collection do
      get :destroy_all
      get :bus
      get :casco
      get :rutas
    end
  end

   match ':controller(/:action(/:id))(.:format)'
end

app/models/gpsejemplo.rb
class Gpsejemplo < ActiveRecord::Base
  attr_accessible :idUsuario, :latitude, :longitude, :timestamp
end

app/models/gpsejemplos.rb
class Gpsejemplos < ActiveRecord::Base
  attr_accessible :idUsuario, :latitude, :longitude, :timestamp
end

app/controllers/gpsejemplos_controller.rb
class GpsejemplosController < ApplicationController
  # GET /gpsejemplos
  # GET /gpsejemplos.json
  def index
    @usuarios = Usuario.all
    @usuarios_json = @usuarios.to_json
  end

  # GET /gpsejemplos/1
  # GET /gpsejemplos/1.json
  def show

  end

  # GET /gpsejemplos/new
  # GET /gpsejemplos/new.json
  def new

  end

  def edit
    @nombre = Usuario.find(params[:id]).nombre
    @gpsejemplo=Gpsejemplo.where(idUsuario: params[:id])
    @gpsejemplo_json=@gpsejemplo.to_json
  end

 def create
    @usuario=Usuario.new(params[:usuario])
    name = params[:usuario]
    nombres=Usuario.where(name)
    if nombres.length==0
      ruta = params[:ruta]
      @usuario.save
      id=@usuario.id
      if(!ruta.eql?(nil))
        arreglo=JSON.parse(ruta)
        for i in 0..arreglo["route"].length-1
          @gpsejemplo=Gpsejemplo.new(:latitude => arreglo["route"][i]["latitude"], :longitude => arreglo["route"][i]["longitude"], :timestamp => arreglo["route"][i]["timestamp"].to_s, :idUsuario => id)
          @gpsejemplo.save
        end
      end
      redirect_to gpsejemplos_path, notice: 'El usuario con su ruta fue agregado satisfactoriamente.'
    else
      redirect_to gpsejemplos_path, notice: 'El usuario ya existe en la base de datos, no se pudo agregar.'
    end
 end

  def rutas
    ids=params[:usua]
    @usuarios=[]
    @pois=[]
    @pois_json=[]
    @coincidencia=[]
    aux=[]
    if(!ids.eql?(nil))
      @usuarios=Usuario.find(ids)
      @pois=Gpsejemplo.where(idUsuario: ids)
      @pois=@pois.order("timestamp")
      radio=params[:radio]
      tiempo=params[:tiempo]
      for i in 0..@pois.length-1
        for j in i..@pois.length-1
          if(!(@pois[i].idUsuario.eql?(@pois[j].idUsuario)))
            dist=distancia(@pois[i].latitude,@pois[i].longitude,@pois[j].latitude,@pois[j].longitude)
            aux=[]
            if(dist<=radio.to_f)
              time=(@pois[i].timestamp.to_f-@pois[j].timestamp.to_f)/1000
              if(time<0)
                time=time*-1
              end
              if(time<=tiempo.to_f)
                aux<<@pois[i]
                aux<<@pois[j]
                @coincidencia<<aux
              end
            end
          end
        end
      end
      #@coincidencia.uniq!
      @pois_json=@pois.to_json
    end
  end
  def distancia(lat1,long1,lat2,long2)
    r= 6378.137
    dLat=(lat1-lat2)*Math::PI/180
    dLong=(long1-long2)*Math::PI/180
    a = Math.sin(dLat/2) * Math.sin(dLat/2) + Math.cos((lat2)*Math::PI/180) * Math.cos((lat1)*Math::PI/180) * Math.sin(dLong/2) * Math.sin(dLong/2)
    c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a))
    d = r * c * 1000
    return d
  end

  def update
    @usuario = Usuario.find(params[:id])

    if @usuario.update_attributes(params[:usuario])
      # redirect the user to index
      redirect_to gpsejemplos_path, notice: 'Location was successfully updated.'
    else
      # redirect the user to the edit method
      render action: 'edit'
    end
  end

  def destroy
    @usuario = Usuario.find(params[:id])
    @gpsejemplo=Gpsejemplo.where(idUsuario: params[:id])
    @gpsejemplo.each do |ejem|
      ejem.destroy
    end
    @usuario.destroy
    redirect_to gpsejemplos_path, notice: 'Usuario was successfully deleted.'
  end
end

app/helpers/gpsejemplos_helper.rb
module GpsejemplosHelper
end

app/views/gpsejemplos/edit.html.haml
/%h1.title Actualizar usuario

/= form_tag gpsejemplos_path(@usuario), :method => :put do

/  = label :usuario, :nombre, 'Nombre:'
/  = text_field :usuario, :nombre
/  %p
/  Ruta:
/  = text_area "", :ruta

/  %p
/  = submit_tag 'Save Changes'

/%p
/= link_to 'Back to location list', gpsejemplos_path

%h1.title Visualizar ruta de usuario:
%h1= @nombre

.map
  %div#map

%input#locations{:type => "hidden", :value => @gpsejemplo_json}

%table#table
  %thead
    %tr
      %th Latitude
      %th Longitude
      %th Timestamp
  %tbody
    - @gpsejemplo.each do |ubicacion|
      %tr
        %td= ubicacion.latitude
        %td= ubicacion.longitude
        %td= ubicacion.timestamp

%p
= link_to 'Back to user list', gpsejemplos_path


= javascript_include_tag '/assets/maps/OpenLayers'
= javascript_include_tag '/assets/maps/locations'
= javascript_include_tag '/assets/maps/jquery-2.0.3.min'

:javascript
  initMap($("#locations").val());

app/views/gpsejemplos/index.html.haml
%h1.title Seleccion para visualizar rutas

%input#locations{:type => "hidden", :value => @gpsejemplos_json}
= form_tag rutas_gpsejemplos_path,:method => :get do
  %table#table
    %thead
      %tr
        %th Seleccion
        %th Nombre
        %th Eliminar
    %tbody
      - @usuarios.each do |usuario|
        %tr
          %td= check_box_tag "usua[]",usuario.id
          %td= usuario.nombre
          %td= link_to "Eliminar", gpsejemplo_path(usuario), :method => :delete, :confirm => 'Are you sure?'
  = label :"", :algo, 'Ventana de distancia (Metros):'
  = text_field_tag :radio, :"50"
  %p
  = label :"", :algo2, 'Ventana de tiempo (Segundos):'
  = text_field_tag :tiempo, :"10"
  %p
  = submit_tag 'Realizar animacion'
  %p

%p=link_to "Crear usuario con una ruta", new_gpsejemplo_path
= link_to 'Back to location list', locations_path
%p= show_flash

app/views/gpsejemplos/new.html.haml
%h1.title Crear usuario con su ruta

= form_tag gpsejemplos_path, :method => :post do

  = label :"", :nombre, 'Nombre'
  = text_field :usuario, :nombre
  %p
  = label :"", :"", 'Ruta'
  = text_area "", :ruta

  %p
  = submit_tag 'Save Changes'

%p
= link_to 'Back to user list', gpsejemplos_path

app/views/gpsejemplos/rutas.html.haml
%h1.title Animacion Rutas Usuarios

.map
  %div#map

%input#locations{:type => "hidden", :value => @pois_json}
-@usuarios.each do |us|
  %h2= "Nombre = "+us.nombre+", ID = "+us.id.to_s
%p
%h2= @mensaje
%h2 Coincidencias de puntos de usuarios
%table#table
  %thead
    %tr
      %th ID usuario
      %th Latitude
      %th Longitude
      %th Timestamp
      %th ID usuario
      %th Latitude
      %th Longitude
      %th Timestamp
  %tbody
    -for i in 0..@coincidencia.length-1
      %tr
        %td= @coincidencia[i][0]["idUsuario"].to_s
        %td= @coincidencia[i][0]["latitude"].to_s
        %td= @coincidencia[i][0]["longitude"].to_s
        %td= @coincidencia[i][0]["timestamp"]
        %td=@coincidencia[i][1]["idUsuario"].to_s
        %td=@coincidencia[i][1]["latitude"].to_s
        %td=@coincidencia[i][1]["longitude"].to_s
        %td=@coincidencia[i][1]["timestamp"]
        /-i=i+1

%p
= link_to 'Back to user list', gpsejemplos_path



= javascript_include_tag '/assets/maps/jquery-2.0.3.min'
= javascript_include_tag '/assets/maps/OpenLayers'
= javascript_include_tag '/assets/maps/locations'

:javascript
  initMap($("#locations").val());

app/views/gpsejemplos/show.html.haml
<h1>Locations#show</h1>
<p>Find me in app/views/locations/show.html.haml</p>